# Generated by Django 5.2.5 on 2025-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Data Analysis', 'Data Analysis'), ('Graphic Design', 'Graphic Design'), ('Content Writing', 'Content Writing'), ('Digital Marketing', 'Digital Marketing'), ('SEO', 'SEO'), ('Other', 'Other'), ('healthcare', 'Healthcare')])),
                ('description', models.CharField(max_length=250)),
                ('pay', models.PositiveIntegerField(choices=[('5,000', '10,000'), ('10,000', '20,000'), ('20,000', '40,000'), ('40,000', '60,000'), ('60,000', '100,000')])),
            ],
        ),
    ]
