# Generated by Django 5.2.5 on 2025-09-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
